const msPerSecond = 1000,
  msPerMin = 60000,
  msPerDay = 86400000;

export enum OutletType {
  ELECTRIC = 'electric',
  HYDRAULIC = 'hydraulic'
}

export enum SensorType {
  WEIGHT = 'weight'
}

export enum OutletState {
  OFF = 0,
  ON = 1
}

export enum OutletStateString {
  OFF = "off",
  ON = "on",
  UNKNOWN = "unknown"
}

const constants = {
  ALL_OUTLET_TYPES: [OutletType.ELECTRIC, OutletType.HYDRAULIC],
  OUTLET_STATE_ON_STRING: "on",
  OUTLET_STATE_OFF_STRING: "off",
  OUTLET_STATE_UNKNOWN_STRING: "unknown",
  SENSOR_TYPE_WEIGHT: 'weight',
  SYSTEM_STATE: {
    INITIALIZING: "INITIALIZING",
    AUTHENTICATING: "AUTHENTICATING",
    SYNCING_TIME: "SYNCING_TIME",
    STARTING_IO_TASK: "STARTING_IO_TASK",
    CONNECTING_WEBSOCKET: "CONNECTING_WEBSOCKET",
    PUBLISHING_CAPABILITIES: "PUBLISHING_CAPABILITIES",
    SIGNAL_DEVICE_BOOT: "SIGNAL_DEVICE_BOOT",
    OPERATING: "OPERATING",
  },
  COMMAND_REFRESHER_STATE: {
    WAITING: "WAITING",
    FETCHING_COMMANDS: "FETCHING_COMMANDS"
  },
  HEARTBEAT_STATE: {
    WAITING: "WAITING",
    SENDING_HEARTBEAT: "SENDING_HEARTBEAT"
  },
  STATE_CHANGE_PRIORITY: {
    NORMAL: "NORMAL",
    HIGHEST: "HIGHEST"
  },
  OUTLET_MIN_SWITCHING_INTERVAL_MS: 2000,
  COMMAND_REFRESH_LEAD_TIME_MS: msPerMin * 30,
  COMMAND_REFRESH_MIN_INTERVAL_MS: 5000,
  COMMAND_REFRESH_MAX_INTERVAL_MS: msPerDay,
  HEARTBEAT_MIN_INTERVAL_MS: 5000,
  HEARTBEAT_MAX_INTERVAL_MS: msPerSecond * 30,
  OUTLET_HISTORY_REPORT_INTERVAL_MS: msPerSecond * 10,
  MAX_LOG_ENTRIES: 200,
  MAX_OUTLET_HISTORY_ENTRIES: 1000,
  MS_PER_SEC: 1000,
  MS_PER_MIN: msPerMin,
  MS_PER_HOUR: 3600000,
  MS_PER_DAY: msPerDay,
  SERVER_EVENTS: {
    SEND_STATUS: "SEND_STATUS",
    NEW_COMMANDS: "NEW_COMMANDS",
  },
};

export default constants;